CREATE TABLE dashboard_pembiayaan(
   vendor_id                VARCHAR(255) NOT NULL PRIMARY KEY
  ,nama_pekerjaan           VARCHAR(255)
  ,nama_vendor              VARCHAR(255)
  ,contract_id              VARCHAR(255)
  ,nomor_spk                VARCHAR(255)
  ,nomor_kontrak            VARCHAR(255)
  ,nilai_kontrak            VARCHAR(255)
  ,jatuh_tempo_pekerjaan    VARCHAR(255)
  ,jenis_pengadaan          VARCHAR(255)
  ,pengadaan_id             VARCHAR(255)
  ,stage_of_work            VARCHAR(255)
  ,termin                   VARCHAR(255)
  ,status_payment           VARCHAR(255)
  ,nilai_termin             VARCHAR(255)
  ,jatuh_tempo_pembayaran   VARCHAR(255)
  ,tanggal_invoice_diterima VARCHAR(255)
);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('945','Pengadaan Perpanjangan Lisensi ABBYY FlexiCapture pada Aplikasi Automatic Document Capture','PT PRISMA TEKNOLOGI INFORMATIKA','2035','PO/0036/2022',NULL,'264550000.00',NULL,'IT','10','Tahap 1','Full Payment',NULL,'264550000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan Maintenance Server Aplikasi BNI Direct DC Slipi Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2004','PO/0002/2022',NULL,'1617000000.00',NULL,'IT','32','Tahap 1','Termin 1',NULL,'479621716.36',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan Maintenance Server Aplikasi BNI Direct DC Slipi Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2004','PO/0002/2022',NULL,'1617000000.00',NULL,'IT','32','Tahap 1','Termin 2',NULL,'284344570.91',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan Maintenance Server Aplikasi BNI Direct DC Slipi Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2004','PO/0002/2022',NULL,'1617000000.00',NULL,'IT','32','Tahap 1','Termin 3',NULL,'284344570.91',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan Maintenance Server Aplikasi BNI Direct DC Slipi Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2004','PO/0002/2022',NULL,'1617000000.00',NULL,'IT','32','Tahap 1','Termin 4',NULL,'284344570.91',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan Maintenance Server Aplikasi BNI Direct DC Slipi Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2004','PO/0002/2022',NULL,'1617000000.00',NULL,'IT','32','Tahap 1','Termin 5',NULL,'284344570.91',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1279','Perpanjangan Tools Monitoring Berbasis Event Log','PT FAN INTEGRASI TEKNOLOGI','2005','PO/0003/2022',NULL,'825000000.00',NULL,'IT','44','Tahap 1','Full Payment',NULL,'575916000.97',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1279','Perpanjangan Tools Monitoring Berbasis Event Log','PT FAN INTEGRASI TEKNOLOGI','2005','PO/0003/2022',NULL,'825000000.00',NULL,'IT','44','Tahap 2','Full Payment',NULL,'186923999.03',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1279','Perpanjangan Tools Monitoring Berbasis Event Log','PT FAN INTEGRASI TEKNOLOGI','2005','PO/0003/2022',NULL,'825000000.00',NULL,'IT','44','Tahap 3','Full Payment',NULL,'62160000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1010','Pengadaan Perangkat IT Non Otomasi Tahun 2022 - Laptop Divisi KOM 2','PT. DATASCRIP','2021','PO/0019/2022',NULL,'399711000.00',NULL,'IT','18','Tahap 1','Full Payment',NULL,'399711000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Perpanjangan maintenance perangkat Router WAN di Gedung Plaza BNI BSD','PT. SWADHARMA DUTA DATA','2008','PO/0008/2022',NULL,'287000000.00',NULL,'IT','47','Tahap 1','Termin 1',NULL,'257008500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Perpanjangan maintenance perangkat Router WAN di Gedung Plaza BNI BSD','PT. SWADHARMA DUTA DATA','2008','PO/0008/2022',NULL,'287000000.00',NULL,'IT','47','Tahap 1','Termin 2',NULL,'29991500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Pengadaaan Maintenance Server DPLK dan Remittance Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2033','PO/0034/2022',NULL,'1850000000.00',NULL,'IT','21','Tahap 1','Termin 1',NULL,'1571575000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Pengadaaan Maintenance Server DPLK dan Remittance Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2033','PO/0034/2022',NULL,'1850000000.00',NULL,'IT','21','Tahap 1','Termin 2',NULL,'278425000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan ITSM untuk Operasional Harian Exadata dan Exalogic','PT. METROCOM GLOBAL SOLUSI','2015','PO/0013/2022',NULL,'2650000000.00',NULL,'IT','9','Tahap 1','Termin 1',NULL,'662500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan ITSM untuk Operasional Harian Exadata dan Exalogic','PT. METROCOM GLOBAL SOLUSI','2015','PO/0013/2022',NULL,'2650000000.00',NULL,'IT','9','Tahap 1','Termin 2',NULL,'662500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan ITSM untuk Operasional Harian Exadata dan Exalogic','PT. METROCOM GLOBAL SOLUSI','2015','PO/0013/2022',NULL,'2650000000.00',NULL,'IT','9','Tahap 1','Termin 3',NULL,'662500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan ITSM untuk Operasional Harian Exadata dan Exalogic','PT. METROCOM GLOBAL SOLUSI','2015','PO/0013/2022',NULL,'2650000000.00',NULL,'IT','9','Tahap 1','Termin 4',NULL,'662500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1335','Perpanjangan sementara kontrak piloting Full Managed Service (FMS) Sewa EDC 500 Unit','PT MITRA TRANSAKSI INDONESIA','2003','PO/0001/2022',NULL,'210000000.00',NULL,'IT','183','Tahap 1','Termin 1',NULL,'210000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan maintenance Hardware Kondor+ dan KTP Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2006','PO/0004/2022',NULL,'950000000.00',NULL,'IT','163','Tahap 1','Full Payment',NULL,'766023198.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan maintenance Hardware Kondor+ dan KTP Tahun 2022','PT. METROCOM GLOBAL SOLUSI','2006','PO/0004/2022',NULL,'950000000.00',NULL,'IT','163','Tahap 2','Full Payment',NULL,'183976802.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1210','Perpanjangan jasa maintenance dan operasional perangkat IP-PBX','CV ATKOMINDO DINAMIKA','2066','PFA/3.2/027',NULL,'1140000000.00',NULL,'IT','177','Tahap 1','Full Payment',NULL,'1140000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1048','Pengadaan perpanjangan maintenance perangkat trading communication system DIvisi Tresuri','PT. MULTI SURYA TUNGGAL','2007','PO/0007/2022',NULL,'757000000.00',NULL,'IT','89','Tahap 1','Full Payment',NULL,'757000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1119','Perpanjangan Maintenance Penambahan Wifi BSD Periode 2022-2025','PT DINAMIKA SISTEM INTEGRASI SOLUSI','2011','PO/0005/2022',NULL,'375000000.00',NULL,'IT','162','Tahap 1','Full Payment',NULL,'195000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1119','Perpanjangan Maintenance Penambahan Wifi BSD Periode 2022-2025','PT DINAMIKA SISTEM INTEGRASI SOLUSI','2011','PO/0005/2022',NULL,'375000000.00',NULL,'IT','162','Tahap 2','Full Payment',NULL,'180000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1335','Pengadaan 38.471 Unit Sewa EDC Full Managed Service (FMS) PT. Mitra Transaksi Indonesia','PT MITRA TRANSAKSI INDONESIA','2010','PO/0006/2022',NULL,'73278021960.00',NULL,'IT','84','Tahap 1','Full Payment',NULL,'73278021960.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('989','Pengadaan Notebook Spesifikasi Khusus Tahun 2022','PT. ALPHA GRAHA COMPUTINDO','2020','PO/0018/2022',NULL,'675000000.00',NULL,'IT','63','Tahap 1','Full Payment',NULL,'675000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1518','Perpanjangan jasa maintenance voice logger untuk unit verifikasi di SKK dan penagihan di RRW periode 2022 sd 2024','PT. PHINTRACO TECHNOLOGY','2009','PO/0009/2022',NULL,'1660000000.00',NULL,'IT','35','Tahap 1','Full Payment',NULL,'1660000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1241','Perpanjangan Maintenance Perangkat Host Security Module (HSM) BI-FAST (CI Connector)','PT SENTRA NETCOMINDO','2019','PO/0017/2022',NULL,'2300000000.00',NULL,'IT','165','Tahap 1','Termin 1',NULL,'2300000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1094','Perpanjangan Maintenance Support Perangkat Safenet HSM Luna EFT2 PL280 Aplikasi Prepaid Card System (Sistem EPurse)','PT. SENTRA PARAMITRA','2018','PO/0016/2022',NULL,'1000000000.00',NULL,'IT','118','Tahap 1','Termin 1',NULL,'1000000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('992','Perpanjangan Maintenance Perangkat Security High Availability IPS untuk pengamanan DC Sudirman dan Slipi','PT. APLIKAS SERVIS PESONA','2012','PO/0010/2022',NULL,'3399282033.00',NULL,'IT','117','Tahap 1','Full Payment',NULL,'2330809685.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('992','Perpanjangan Maintenance Perangkat Security High Availability IPS untuk pengamanan DC Sudirman dan Slipi','PT. APLIKAS SERVIS PESONA','2012','PO/0010/2022',NULL,'3399282033.00',NULL,'IT','117','Tahap 2','Termin 2',NULL,'368190315.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('992','Perpanjangan Maintenance Perangkat Security High Availability IPS untuk pengamanan DC Sudirman dan Slipi','PT. APLIKAS SERVIS PESONA','2012','PO/0010/2022',NULL,'3399282033.00',NULL,'IT','117','Tahap 3','Full Payment',NULL,'700282033.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1521','Perpanjangan Pemeliharaan New Website BNI','PT. PLEXIS ERAKARSA PIRANTINIAGA','2013','PO/0011/2022',NULL,'288000000.00',NULL,'IT','171','Tahap 4','Termin 1',NULL,'72000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1521','Perpanjangan Pemeliharaan New Website BNI','PT. PLEXIS ERAKARSA PIRANTINIAGA','2013','PO/0011/2022',NULL,'288000000.00',NULL,'IT','171','Tahap 4','Termin 2',NULL,'72000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1521','Perpanjangan Pemeliharaan New Website BNI','PT. PLEXIS ERAKARSA PIRANTINIAGA','2013','PO/0011/2022',NULL,'288000000.00',NULL,'IT','171','Tahap 4','Termin 3',NULL,'72000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1521','Perpanjangan Pemeliharaan New Website BNI','PT. PLEXIS ERAKARSA PIRANTINIAGA','2013','PO/0011/2022',NULL,'288000000.00',NULL,'IT','171','Tahap 4','Termin 4',NULL,'72000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1034','Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','PT. LAPI ITB','2014','PO/0012/2022',NULL,'235000000.00',NULL,'Premises','24','Tahap 1','Termin 1',NULL,'47000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1034','Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','PT. LAPI ITB','2014','PO/0012/2022',NULL,'235000000.00',NULL,'Premises','24','Tahap 2','Termin 2',NULL,'47000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1034','Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','PT. LAPI ITB','2014','PO/0012/2022',NULL,'235000000.00',NULL,'Premises','24','Tahap 3','Termin 3',NULL,'47000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1034','Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','PT. LAPI ITB','2014','PO/0012/2022',NULL,'235000000.00',NULL,'Premises','24','Tahap 4','Termin 4',NULL,'47000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1034','Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','PT. LAPI ITB','2014','PO/0012/2022',NULL,'235000000.00',NULL,'Premises','24','Tahap 5','Termin 5',NULL,'35250000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1034','Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','PT. LAPI ITB','2014','PO/0012/2022',NULL,'235000000.00',NULL,'Premises','24','Tahap 6','Termin 6',NULL,'11750000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1096','Pengadaan Perangkat IT Non Otomasi Tahun 2022 - Notebook WEM','PT. PURA BARUTAMA','2016','PO/0014/2022',NULL,'447000000.00',NULL,'IT','111','Tahap 1','Full Payment',NULL,'447000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1262','Pengadaan PC Spesifikasi Khusus Tahun 2022','PT WORLD INFINITE NETWORK','2017','PO/0015/2022',NULL,'2458000000.00',NULL,'IT','64','Tahap 1','Full Payment',NULL,'2458000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1043','Perpanjangan Maintenance Whitelisting Untuk Mesin ATM','PT. MITRA INTEGRASI INFORMATIKA','2022','PO/0021/2022',NULL,'1590084100.00',NULL,'IT','220','Tahap 1','Full Payment',NULL,'1103904100.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1043','Perpanjangan Maintenance Whitelisting Untuk Mesin ATM','PT. MITRA INTEGRASI INFORMATIKA','2022','PO/0021/2022',NULL,'1590084100.00',NULL,'IT','220','Tahap 2','Full Payment',NULL,'111000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1043','Perpanjangan Maintenance Whitelisting Untuk Mesin ATM','PT. MITRA INTEGRASI INFORMATIKA','2022','PO/0021/2022',NULL,'1590084100.00',NULL,'IT','220','Tahap 3','Full Payment',NULL,'375180000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1046','Perpanjangan Lisensi Virtualisasi Server Development Cardlink','PT. MITRA MANDIRI INFORMATIKA','2023','PO/0023/2022',NULL,'2950000000.00',NULL,'IT','92','Tahap 1','Termin 1',NULL,'2486225730.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1046','Perpanjangan Lisensi Virtualisasi Server Development Cardlink','PT. MITRA MANDIRI INFORMATIKA','2023','PO/0023/2022',NULL,'2950000000.00',NULL,'IT','92','Tahap 1','Termin 2',NULL,'463774270.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Pengadaan Perangkat Management Firewall di DC Sudirman dan DC Slipi','PT. SWADHARMA DUTA DATA','2024','PO/0022/2022',NULL,'2500000000.00',NULL,'IT','48','Tahap 1','Termin 1',NULL,'2043982802.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Pengadaan Perangkat Management Firewall di DC Sudirman dan DC Slipi','PT. SWADHARMA DUTA DATA','2024','PO/0022/2022',NULL,'2500000000.00',NULL,'IT','48','Tahap 1','Termin 2',NULL,'356017198.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Pengadaan Perangkat Management Firewall di DC Sudirman dan DC Slipi','PT. SWADHARMA DUTA DATA','2024','PO/0022/2022',NULL,'2500000000.00',NULL,'IT','48','Tahap 1','Termin 3',NULL,'100000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1079','Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Jakarta Timur dengan PT Swadharma Sarana Informatika (No. PKS awal 12/PKS/PFA/2021 Tanggal 25 Juli 2022)','PT. SWADHARMA SARANA INFORMATIKA','2068','PFA/2.3/042',NULL,'492883376.00',NULL,'Non IT','149','Tahap 1','Full Payment',NULL,'492883376.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('990','Perpanjangan Maintenance Infrastruktur Anti Money Laundering (AML) 2022','PT. ANABATIC TECHNOLOGIES TBK','2025','PO/0024/2022',NULL,'2275000000.00',NULL,'IT','38','Tahap 1','Full Payment',NULL,'1299935000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('990','Perpanjangan Maintenance Infrastruktur Anti Money Laundering (AML) 2022','PT. ANABATIC TECHNOLOGIES TBK','2025','PO/0024/2022',NULL,'2275000000.00',NULL,'IT','38','Tahap 2','Termin 1',NULL,'243652500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('990','Perpanjangan Maintenance Infrastruktur Anti Money Laundering (AML) 2022','PT. ANABATIC TECHNOLOGIES TBK','2025','PO/0024/2022',NULL,'2275000000.00',NULL,'IT','38','Tahap 2','Termin 2',NULL,'243652500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('990','Perpanjangan Maintenance Infrastruktur Anti Money Laundering (AML) 2022','PT. ANABATIC TECHNOLOGIES TBK','2025','PO/0024/2022',NULL,'2275000000.00',NULL,'IT','38','Tahap 2','Termin 3',NULL,'243652500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('990','Perpanjangan Maintenance Infrastruktur Anti Money Laundering (AML) 2022','PT. ANABATIC TECHNOLOGIES TBK','2025','PO/0024/2022',NULL,'2275000000.00',NULL,'IT','38','Tahap 2','Termin 4',NULL,'244107500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1049','Perpanjangan maintenance Tool Monitoring Whatsup Gold (WUG 2022-2023)','PT. MULTIPOLAR TECHNOLOGY TBK','2026','PO/0025/2022',NULL,'415140000.00',NULL,'IT','39','Tahap 1','Termin 1',NULL,'415140000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1103','Perpanjangan Maintenance Annual Technical Support (ATS) Oracle Database untuk BI-RTGS','PT. METROCOM GLOBAL SOLUSI','2044','PO/0027/2022',NULL,'982800000.00',NULL,'IT','71','Tahap 1','Full Payment',NULL,'982800000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Perpanjangan Jasa Operasional Harian untuk Mendukung Layanan BNI e-Payment','PT. SWADHARMA DUTA DATA','2046','PO/0047/2022',NULL,'955000000.00',NULL,'IT','82','Tahap 1','Pembayaran Parsial',NULL,'955000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1043','Perpanjangan Lisensi Berlangganan dan Jasa Pemeliharaan Perangkat Lunak Platform Container Service BNI Cloud','PT. MITRA INTEGRASI INFORMATIKA','2050','PO/0049/2022',NULL,'2053951770.00',NULL,'IT','83','Tahap 1','Termin 1',NULL,'1876284941.90',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1043','Perpanjangan Lisensi Berlangganan dan Jasa Pemeliharaan Perangkat Lunak Platform Container Service BNI Cloud','PT. MITRA INTEGRASI INFORMATIKA','2050','PO/0049/2022',NULL,'2053951770.00',NULL,'IT','83','Tahap 2','Termin 2',NULL,'177666828.11',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1043','Pengadaan Kuota Lisensi Davis Data Unit APM Dynatrace untuk Monitoring Aplikasi SOA','PT. MITRA INTEGRASI INFORMATIKA','2049','PO/0050/2022',NULL,'220000000.00',NULL,'IT','13','Tahap 1','Full Payment',NULL,'220000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('987','Pengadaan jasa instalasi environment development Base24 di mesin tandem NB56000 DRC','PT. ABHIMATA PERSADA','2036','PO/0026/2022',NULL,'400000000.00',NULL,'IT','127','Tahap 1','Full Payment',NULL,'262500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('987','Pengadaan jasa instalasi environment development Base24 di mesin tandem NB56000 DRC','PT. ABHIMATA PERSADA','2036','PO/0026/2022',NULL,'400000000.00',NULL,'IT','127','Tahap 2','Full Payment',NULL,'137500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1017','Pengadaan Buku Tabungan BNI Taplus Tahun 2022','PT. GRAFICINDO MEGAH UTAMA','2032','PO/0031/2022',NULL,'1792500000.00',NULL,'Non IT','203','Tahap 1','Full Payment',NULL,'1792500000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1094','Pengadaan perpanjangan sementara sewa jasa content delivery network (CDN) dan fitur security untuk akses Ibank, BNIDirect dan Web BNI','PT. SENTRA PARAMITRA','2034','PO/0035/2022',NULL,'950160000.00',NULL,'IT','75','Tahap 1','Full Payment',NULL,'950160000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1529','Perpanjangan Maintenance dan Support Advanced Anti Malware DC Slipi','PT. PRIMA INTEGRASI NETWORK','2048','PO/0048/2022',NULL,'1584000000.00',NULL,'IT','110','Tahap 1','Termin 1',NULL,'1439856000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1529','Perpanjangan Maintenance dan Support Advanced Anti Malware DC Slipi','PT. PRIMA INTEGRASI NETWORK','2048','PO/0048/2022',NULL,'1584000000.00',NULL,'IT','110','Tahap 1','Termin 2',NULL,'144144000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('2105','Pengadaan Jasa Pengembangan Fitur dan Maintenance System IDEAS','CRIF','2047','PO/0046/2022',NULL,'2100000000.00',NULL,'IT','56','Tahap 2','Termin 1',NULL,'1050000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('2105','Pengadaan Jasa Pengembangan Fitur dan Maintenance System IDEAS','CRIF','2047','PO/0046/2022',NULL,'2100000000.00',NULL,'IT','56','Tahap 2','Termin 2',NULL,'1050000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1049','Perpanjangan Maintenance Server IBM Power 8 Untuk Sistem Aplikasi SOA','PT. MULTIPOLAR TECHNOLOGY TBK','2038','PO/0039/2022',NULL,'2398000000.00',NULL,'IT','237','Tahap 1','Termin 1',NULL,'1998000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Pengadaan Bandwidth Management Internet Campus LAN  Menara-BSD dan Grha','PT. SWADHARMA DUTA DATA','2037','PO/0038/2022',NULL,'3270000000.00',NULL,'IT','36','Tahap 1','Termin 1',NULL,'2720000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Pengadaan Bandwidth Management Internet Campus LAN  Menara-BSD dan Grha','PT. SWADHARMA DUTA DATA','2037','PO/0038/2022',NULL,'3270000000.00',NULL,'IT','36','Tahap 1','Termin 2',NULL,'100000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Pengadaan Bandwidth Management Internet Campus LAN  Menara-BSD dan Grha','PT. SWADHARMA DUTA DATA','2037','PO/0038/2022',NULL,'3270000000.00',NULL,'IT','36','Tahap 1','Termin 3',NULL,'50000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1082','Perpanjangan sewa jaringan komunikasi Kantor Cabang Luar Negeri (KCLN) dan konfirmasi terminasi jaringan KCLN Tokyo','PT. TELEKOMUNIKASI INDONESIA TBK','2040','PO/0040/2022',NULL,'2698632000.00',NULL,'IT','197','Tahap 1','Termin 1',NULL,'2698632000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1082','Perpanjangan Sewa Jaringan Komunikasi DWDM DC Sudirman - DC Slipi Kapasitas 10 Gbps','PT. TELEKOMUNIKASI INDONESIA TBK','2039','PO/0041/2022',NULL,'6669687273.00',NULL,'IT','1','Tahap 1','Termin 1',NULL,'6669687273.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1833','Pengadaan Professional Integrated Display Monitoring Perangkat Keamanan Informasi','PT MILAND CIPTA USAHA','2041','PO/0043/2022',NULL,'204000000.00',NULL,'IT','262','Tahap 1','Full Payment',NULL,'200000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1833','Pengadaan Professional Integrated Display Monitoring Perangkat Keamanan Informasi','PT MILAND CIPTA USAHA','2041','PO/0043/2022',NULL,'204000000.00',NULL,'IT','262','Tahap 2','Full Payment',NULL,'4000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('990','Perpanjangan Lisensi & Maintenance IBM Websphere Application Server Untuk Aplikasi ePurse','PT. ANABATIC TECHNOLOGIES TBK','2042','PO/0044/2022',NULL,'690000000.00',NULL,'IT','274','Tahap 1','Full Payment',NULL,'690000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1022','Perpanjangan dan upgrade sewa jaringan komunikasi internet primary DRC Jatiluhur','PT. INDOSAT TBK.','2043','PO/0045/2022',NULL,'530176364.00',NULL,'IT','192','Tahap 1','Termin 1',NULL,'530176364.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1094','Perpanjangan Maintenance Perangkat Security IPS DC Sudirman','PT. SENTRA PARAMITRA','2067','PFA/02039/2023/0702',NULL,'1400000000.00',NULL,'IT','245','Tahap 1','Termin 1',NULL,'1400000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1076','Perpanjangan Jasa Pemeliharaan CCOS Tahun 2023','PT. SWADHARMA DUTA DATA','2053','PO/0053/2022',NULL,'557000000.00',NULL,'IT','247',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','Pengadaan Gedung Baru 2023','PT. INFOSYS SOLUSI TERPADU','2056','PO/0056/2023',NULL,'98000000.00',NULL,NULL,'422','Tahap 1','Termin 1',NULL,'90000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','Pengadaan Gedung Baru 2023','PT. INFOSYS SOLUSI TERPADU','2056','PO/0056/2023',NULL,'98000000.00',NULL,NULL,'422','Tahap 2','Termin 2',NULL,'8000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('987','Perpanjangan Jasa Pemeliharaan dan Dukungan Teknis System Switching BNI','PT. ABHIMATA PERSADA','2057','PO/0057/2023',NULL,'49500000000.00',NULL,'IT','120',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1032','Jasa Konstruksi Pekerjaan Relayout Ruang Kerja Divisi DGO Menara BNI lantai 19,20,dan 26','PT. KARYA MENTARI SERAYA','2058','PO/0058/2023',NULL,'1800000000.00',NULL,'Premises','138',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('762','Pelatihan Mindfulness untuk Program Kepemimpinan BNI','PT ARGA BANGUN BANGSA','2059','PO/0059/2023',NULL,'897582500.00',NULL,'Pelatihan dan Konsultan','100','Tahap 1','Termin 1',NULL,'97582500.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('762','Pelatihan Mindfulness untuk Program Kepemimpinan BNI','PT ARGA BANGUN BANGSA','2059','PO/0059/2023',NULL,'897582500.00',NULL,'Pelatihan dan Konsultan','100','Tahap 2','Termin 1',NULL,'800000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','Pengadaan WO Application 2023','PT. INFOSYS SOLUSI TERPADU','2063','SPK/2023/01/31-01',NULL,'300000000.00',NULL,NULL,'431','Tahap 1','Full Payment',NULL,'100000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','Pengadaan WO Application 2023','PT. INFOSYS SOLUSI TERPADU','2063','SPK/2023/01/31-01',NULL,'300000000.00',NULL,NULL,'431','Tahap 2','Termin 1',NULL,'200000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1026','2 tahap tender terbatas  Nego Daring Auction Merit Point Harga Total Single Winner','PT. INTIKOM BERLIAN MUSTIKA','2060','PO/0060/2023',NULL,'260000000.00',NULL,NULL,'428','Tahap 1','Full Payment',NULL,'260000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1082','Pengadaan Mudah TESTING','PT. TELEKOMUNIKASI INDONESIA TBK','2061','PO/0061/2023',NULL,'900000000.00',NULL,'IT','435','Tahap 1','Full Payment',NULL,'900000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','satu sampul Testing','PT. INFOSYS SOLUSI TERPADU','2062','PO/0062/2023',NULL,'92000000.00',NULL,'IT','444','Tahap 1','Termin 1',NULL,'92000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','Pengadaan Multiwinner 2023','PT. INFOSYS SOLUSI TERPADU','2065','PFA.02938812.2023.06',NULL,'180000000.00',NULL,NULL,'441','Tahap 1','Termin 1',NULL,'100000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1024','Pengadaan Multiwinner 2023','PT. INFOSYS SOLUSI TERPADU','2065','PFA.02938812.2023.06',NULL,'180000000.00',NULL,NULL,'441','Tahap 2','Termin 1',NULL,'80000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1026','Pengadaan Multiwinner 2023','PT. INTIKOM BERLIAN MUSTIKA','2064','PFA.029383.0039181',NULL,'560000000.00',NULL,NULL,'441','Tahap 1','Full Payment',NULL,'280000000.00',NULL,NULL);
INSERT INTO dashboard_pembiayaan(vendor_id,nama_pekerjaan,nama_vendor,contract_id,nomor_spk,nomor_kontrak,nilai_kontrak,jatuh_tempo_pekerjaan,jenis_pengadaan,pengadaan_id,stage_of_work,termin,status_payment,nilai_termin,jatuh_tempo_pembayaran,tanggal_invoice_diterima) VALUES ('1026','Pengadaan Multiwinner 2023','PT. INTIKOM BERLIAN MUSTIKA','2064','PFA.029383.0039181',NULL,'560000000.00',NULL,NULL,'441','Tahap 2','Full Payment',NULL,'280000000.00',NULL,NULL);
