CREATE TABLE monitoring_pembayaran_rutin(
    ID int NOT NULL PRIMARY KEY
   ,NAMA VARCHAR(255)
   ,NILAI_PENGADAAN_HASIL VARCHAR(255)
   ,Pembayaran_Terakhir VARCHAR(255)
   ,Status_Jatuh_Tempo VARCHAR(255)
   ,CONSTRAINT pk_monitoring_proses_monitoring_pembayaran_rutinPRIMARY KEY (ID)
);


-- Step 2: Create the sequence
CREATE SEQUENCE monitoring_pembayaran_rutin_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Step 3: Create the trigger
CREATE OR REPLACE TRIGGER monitoring_pembayaran_rutin_bir
BEFORE INSERT ON monitoring_pembayaran_rutin
FOR EACH ROW
BEGIN
    SELECT monitoring_pembayaran_rutin_seq.NEXTVAL INTO :NEW.ID FROM dual;
END;


INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pintu Khasanah Untuk KCP Gunung Sahari',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Upgrade Storage Untuk Sistem Aplikasi Cardlink',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Pengawasan Pekerjaan Relayout Ruang Kerja Divisi DGO Menara BNI lantai 19,20,dan 26','169000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Storage NAS DC dan DRC',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Pengawasan Pekerjaan Renovasi Relokasi KC Senayan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Pengelolaan dan Pemeliharaan Gedung BNI Corporate University (BCV) Slipi Selama 6 (Enam) Bulan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Pemasangan Iklan pada Media Luar Ruang LED Jl. By Pass Ida Bagus Mantra Bali',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Penambahan Modul Share Class Pada Aplikasi Medallion Fund Service',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Maintenance Mesin Personalisasi Kartu Datacard MX6000 & UPS',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Tenaga Alih Daya Jasa Pengamanan Kantor Pusat Tahun 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan konsolidasi maintennace infrastruktur server mesin exalogic dan exadata tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan sewa jaringan komunikasi backup DWDM DC Sudirman - DRC kapasitas 10 Gbps',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Jakarta Selatan dengan PT Nawakara Arta Kencana (No. PKS awal 16/PKS/PFA/2021 Tanggal 25 Juli 2022)','507127173.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Bogor dengan PT Nawakara Arta Kencana (No. PKS awal 18/PKS/PFA/2021 Tanggal 25 Juli 2022)','459078735.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penyedia Layanan Pengiriman SMS OTP 3D Secure Kartu Debit BNI dan Kartu Kredit BNI Desember 2022 - Desember 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jaringan Internet Backup di Cabang (75 Lokasi SDWAN)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan sementara kontrak piloting Full Managed Service (FMS) Sewa EDC 500 Unit','210000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Jasa Tele-Usage Loan On Phone Kartu Kredit BNI (Periode 01 Mei sd 30 Juni 2022)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Sewa Jaringan Internet Area Ballroom Menara BNI Pejompongan (Primary dan Secondary)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Mesin Enterprise Data Warehouse (EDW) Appliance di DC Slipi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Aplikasi Automated Report Management',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Transceiver untuk Kebutuhan Improvement Koneksi Switch Server Farm antar DRC',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Pembangunan 4 (empat) Rumah Dinas Jalan Gandaria Tengah VI Jakarta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Blank Card Kartu Private Label Non Chip Kartu Debit BNI Simpel sebanyak 300.000 pcs kartu',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Jasa Manage Service Aplikasi Manajemen Sosial Media','278000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Repeat Order Pengadaan Penambahan Server untuk Aplikasi Fraud Detection System (FDS)','1250000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Microservice Catalog Tools',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Renovasi Toilet Holding Room Menara BNI lantai 6',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Repeat Order Pengadaan Jasa Instalasi dan Relokasi LAN Building dan Backbone Data Center',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Repeat Order Pengadaan Perangkat Otomasi Mesin Pembukaan Rekening (DIGICS d/h BNI Sonic)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Replace Dealing Phone Tresuri di Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Server Network Attached Storage (NAS)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Jakarta Pusat)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Jakarta Barat)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Jakarta Utara)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Bogor)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Pemeliharaan Software Replikasi Untuk System Aplikasi Platform X86',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Pelatihan Kepemimpinan Untuk Advanced Management Leadership Program (AMLP)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Cek dan Bilyet Giro untuk Masa Pengadaan Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Kerjasama Telekomunikasi melalui Provider Session Initiation Protocol (SIP ) di Kantor Besar BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Aplikasi 2023 ( UAT )',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengadaan IT - 28122022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 27122022 2','52500000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengadaan Pengumuman - pimkel',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengadaan ET - dgm',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 30122022 I',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - 05012022 - 02',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Gedung Baru 2023','98000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('2 tahap tender terbatas  Nego Daring Auction Merit Point Harga Total Single Winner','260000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan MW Gedung Februari 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test BA price eval',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penyesuaian Official Report - Tender',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT UCP Di Atas 500 Juta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Testing dibawah 500 juta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('testing diatas 500 juta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan UAT Konsultan Lainnya',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan UAT Konsultan Konstruksi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Modul API Management AXWAY suite 5',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Perencanaan Pekerjaan Perbaikan Gondola di Plaza BNI BSD',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Bandwidth Management Internet Campus LAN  Menara-BSD dan Grha','2870000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Penetration Testing Transaksional dan Kritikal BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengembangan Fitur dan Maintenance System IDEAS','2100000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('jasa pelaksana renovasi sarana & prasarana BCV Kota',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat IT Non Otomasi Tahun 2022 - Notebook WEM','447000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Pemeliharaan dan Dukungan Teknis System Switching BNI','49500000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan pemasangan iklan pada media luar ruang LED Jl. Ahmad Yani Bekasi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Produksi Kalender Meja BNI Edisi Tahun 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Maintenance Aplikasi Control-M',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Improvement Jasa Assessment Penetration Testing Regular Peningkatan Keamanan Sistem Digital Banking BNI Periode 2022-2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Perangkat Host Security Module (HSM) BI-FAST (CI Connector)','2300000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Mesin Enterprise Data Warehouse (EDW) Appliance di DRC Jatiluhur',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan dan upgrade sewa jaringan komunikasi internet primary DRC Jatiluhur','530176364.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan sewa jaringan komunikasi Kantor Cabang Luar Negeri (KCLN) dan konfirmasi terminasi jaringan KCLN Tokyo','2698632000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Renovasi Ruang Kerja Divisi OPR Kelompok KKR di Gedung Grha BNI Lantai 21',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Perbaikan Atap dan Instalasi Listrik Rumah Jabatan Griya Simprug Area A, C, dan E',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan pemasangan iklan pada media luar ruang LED Mall Ratu Indah Makassar',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Partial Relayout Ruang Kerja Divisi Compliance',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Renovasi Ruang Kerja & Kelas Lantai 1-3 Gedung Dekan 1',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perpanjangan pengelolaan dan pemeliharaan Rumah Instansi BNI Jakarta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultansi Pengawasan Pekerjaan Penggantian Cooling Tower 10 dan 11 pada Gedung Grha BNI Sudirman',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Monitoring dan Perlindungan Cyber (Ulangan)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Brand Consultant BNI Emerald Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan (Renewal) Maintenance dan Lisensi Perangkat Lunak (Software) Big Data',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengelolaan & Pemeliharaan Bangunan BCM Purwakarta, Bukit Pelangi dan Cibogo',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Upgrade Sewa Jaringan Internet Operasional Office Gedung Grha Sudirman (Primary & Secondary)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa IT Service Management Perangkat Load Balancer F5 Data Center BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Jakarta Selatan)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Serang)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Lanjutan Renovasi Interior Rumah Jabatan Jl. Sriwijaya V No. 1',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultansi Manajemen Konstruksi Pekerjaan Relayout Outlet Emerald Central Park',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan loose furniture ruang kerja COB3 di lantai 3 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perpanjangan konsultan jasa executive search (head hunter)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Instalasi Kabel FO Lt.14 menuju Lt.6 Menara Pejompongan untuk Keperluan Event BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Jasa Pengelolaan dan Pemeliharaan Gedung BNI Corporate University selama 3 bulan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Error saat kirim pembukaan penawaran tahap 1',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 27122022 - UAT',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test evaluasi harga',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Uji - Pengadaan 28122022 - pimkel',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('pengadaan evaluasi harga friska',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Uji - Pengadaan Pengumuman Tender - 10012023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Uji - Pengadaan Pengumuman Tender - 10012023 - 02',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test proses bisnis',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('2 Tahap Tender Negosiasi manual Bidding Passing grade,harga satuan multiwinner mata uang tunggal non prakualifikasidrtunondrtu Tender',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Workflow Approval Gagal 0 -100 jt',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Bismillah fix Pengadaan Cancel Reject',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Template',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT Note UCP',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT Teknis Di Bawah 500 Juta 2',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Renovasi Sarana dan Prasarana BCV Slipi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultan Lead Advisor "Project Oasis"',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengelolaan LED Indoor Menara BNI Pejompongan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Usul pengadaan perpanjangan pengelolaan LED Kanwil Bandung',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Manajemen Konstruksi Pekerjaan Pembangunan Gedung Kanwil 16 dan KC Jayapura',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Office Automation Server Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perangkat IT non otomasi tahun 2022 (TV) Divisi Bisnis Komersial 2','102000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Sewa Jaringan Internet Produktivitas Kantor BNI BSD 200 Mbps',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Notebook Spesifikasi Khusus Tahun 2022','675000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Annual Technical Support (ATS) Oracle Database untuk BI-RTGS','982800000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Buku Tabungan BNI Tapenas Tabungan Yadnya 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Server Pedoman Perusahaan (PP) Online',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Jasa Operational Service Operation',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Pemeliharaan (Kontrak Servis) HVAC Gedung Grha Sudirman','590000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan AC Cassette Satuan Anti Fraud',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Support Perangkat Safenet HSM Luna EFT2 PL280 Aplikasi Prepaid Card System (Sistem EPurse)','1000000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan jasa instalasi environment development Base24 di mesin tandem NB56000 DRC','400000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan workstation dan kursi ruang kerja Div KPS2 di lt 11 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Jakarta Pusat dengan PT Sectoor Indonesia (No. PKS awal 10/PKS/PFA/2021 Tanggal 25 Juli 2022)','633846384.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Karawang dengan PT Nawakara Arta Kencana (No. PKS awal 17/PKS/PFA/2021 Tanggal 25 Juli 2022)','386906876.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Jakarta Utara dengan PT Advantage SCM (No. PKS awal 21/PKS/PFA/2021 Tanggal 25 Juli 2022)','411416426.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengiriman (Kurir) Agenda & Kalender BNI Edisi Tahun 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Aplikasi Telesales',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan workstation dan kursi ruang kerja Divisi Sindikasi dan Solusi Korporasi di lantai 19 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Backup Data untuk Sistem Aplikasi Kartu Kredit',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Penambahan Lisensi Berlangganan Sistem Operasi Linux dan Application Runtime Red Hat Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Blank card Kartu Debit Chip NSICCS Private Label Combo Tapcash sebanyak 40.000 pcs kartu','1800000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Sewa Kendaraan Motor Listrik Untuk Kendaraan Operasional Pengawasan Pemeliharaan Gedung Divisi PFA dan Pengawasan Pemeliharaan Gedung di Wilayah Jabodetabek',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pekerjaan Jasa Pemeliharaan (Kontrak Servis) HVAC Gedung Grha Sudirman',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Pelatihan Tematik Business Banking Segmen Kecil sd Rp1 Miliar Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Sewa Jaringan Komunikasi Internet Secondary DRC Jatiluhur',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Perangkat Aspect Predictive Dialer System (PDS) di 7 Kota',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Blank Card Kartu Debit Chip Mastercard sebanyak 50.000 pcs Kartu','2400000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultan Optimalisasi Otomasi Proses Development Source Code',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Aplikasi Security Internal Monitoring (Systemskan) Periode 2023-2024',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Manajemen Konstruksi Renovasi KC Jakarta Pusat',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Sewa Jarkom Mobile M2M O-Branch Tahun 2023 Sebanyak 180 Unit',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Upgrade Sewa Jaringan Komunikasi Internet DC Slipi (Secondary Link) 500 Mbps',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Audit Building Gedung BNI Diponegoro Denpasar',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan maintenance perangkat server IBM Power 8 DC & DRC',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Penambahan Scope Kerja Konsultan Enterprise Financial System Assessmen',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 26122022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 29122022 I',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 29122022 II',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengumuman Tender Terbatas - 10012023 - 01',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test 2 tahap MultiWinner',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Gedung Sekolah 2023 ( UAT )',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Mudah TESTING','900000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Multiwinner 2023','838000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test PM Negosiasi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('2 Tahap Testing',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Workflow Approval Gagal 101 - 500 jt',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test lagi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test re-held 2 tahap',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test re-held 1  sampul',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('test note',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Testing catatan inisiasi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT Teknis Di Atas 500 Juta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test 1 Penagdaan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test 3 Pengadaan - Pelaksana Kontraktor',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('test pengadaan konsultan konstruksi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Barang Jadi (Distributor)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan UAT Revisi HPS',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Treatment Lantai dan Sistem Pendingin Ruang Server Ruang Kerja Direksi dan SEVP Wisma 46',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Seragam Batik Corporate Frontliner','1479000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Perencanaan Desain Detail Pekerjaan Pembangunan Gedung Kanwil 16 dan KC Jayapura',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Server Aplikasi BNI Direct DC Slipi Tahun 2022','1617000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Infrastruktur Anti Money Laundering (AML) 2022','2275000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan pemenuhan perangkat Enkripsi Dekripsi Mobile Banking DMZ Data Center BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Management Firewall di DC Sudirman dan DC Slipi','2500000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjang Kontrak Sewa EDC 48.000 Unit',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Agency Creative In-House',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Tenaga Alih Daya (TAD) Sales Company Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Agenda reguler tahun 2023 sebanyak 110.000 buku',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Maintenance SSL Termination DC Slipi (Primary & Secondary)','1215000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Tenaga Alih Daya Jasa Lainnya Kantor Pusat Tahun 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pekerjaan Pemasangan Partisi Lipat Lantai 9 Plaza BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan sewa jaringan komunikasi backup DWDM DC Sliipi - DRC kapasitas 10 Gbps',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Depok dengan PT Sectoor Indonesia (No. PKS awal 09/PKS/PFA/2021 Tanggal 25 Juli 2022)','367433177.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Jakarta Timur dengan PT Swadharma Sarana Informatika (No. PKS awal 12/PKS/PFA/2021 Tanggal 25 Juli 2022)','492883376.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Serang dengan PT Swadharma Sarana Informatika (No. PKS awal 14/PKS/PFA/2021 Tanggal 25 Juli 2022)','167673418.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Penambahan Wifi BSD Periode 2022-2025','375000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penambahan Perangkat Accesspoint Wifi Pegawai',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Maintenance Perangkat Storage IBM DS8886 Core Banking DC - DRC Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Whitelisting Untuk Mesin ATM','2218198870.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Maintenance 125 Unit BNI DigiCS',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan jasa konsultansi perencanaan penggantian Cooling Tower 10 dan 11 Gedung Grha BNI Sudirman',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Gadget (Device Mobile) dan Service Environment Pendukung Implementasi BNIMove','2814405000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultan Job Description',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Built In Furniture Ruang Kerja Direksi dan Komisaris di Lantai 28 s.d. 31 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Perangkat Security IPS DC Sudirman','1400000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pemasangan Iklan pada Media Luar Ruang Neonbox Bandara Internasional Kualanamu Deli Serdang - Sumatera Utara',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Atensi Natal BNI Emerald Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Professional Integrated Display Monitoring Perangkat Keamanan Informasi','204000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Pelatihan Financial Analysis',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Lisensi & Maintenance IBM Websphere Application Server Untuk Aplikasi ePurse','690000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Office Automation Switch Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Jakarta Timur)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultan Pengurusan Perizinan IMB Rumah Jabatan Jalan Jambu No.49',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Improvement Privileged Access Management untuk Peningkatan Keamanan System BNI (Tahap II)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengembangan CCOS Untuk Integrasi Dengan Smartdigi Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengelolaan & Pemeliharaan Gedung BNI Corporate University (BCV) Slipi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Pengadaan Konsultan Jasa Executive Search (Head Hunter)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 26122022 ke 2',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test tombol export vendor pendaftaran pengadaan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - 6012023 - 1','900000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('test',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengumuman Tender - 10012023 - 01',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Server Testing Eproc',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test pengadaan cancel error AST',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Workflow Approval Cancel 101 - 500 jt',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Multi winner test','300000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT 22052023  (Pemasuka Penawaran)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Uat catatan inisiasi diatas 500 juta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test Pengadaan Konsultan Lainnya',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Sewa Jaringan Komunikasi DWDM DC Sudirman - DC Slipi Kapasitas 10 Gbps','6669687273.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan maintenance perangkat security gedung BNI Pejompongan Periode 2022-2024',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Kuota Lisensi Davis Data Unit APM Dynatrace untuk Monitoring Aplikasi SOA','220000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Pemeliharaan Water Treatment Cooling Tower Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan LED Merdeka Polrestabes Bandung',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Assesment Kelayakan Data Center Sudirman',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan jasa maintenance voice logger untuk unit verifikasi di SKK dan penagihan di RRW periode 2022 sd 2024','1660000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penambahan Kapasitas Storage untuk Sistem Aplikasi SOA DC dan DRC',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan maintenance Tool Monitoring Whatsup Gold (WUG 2022-2023)','415140000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Instalasi Kabel LAN & Backbone Data Center Slipi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Manajemen Konstruksi Pekerjaan Relayout Ruang Kerja Divisi Pengembangan Digital (DGL)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Sewa Jaringan Internet Menara BNI Penjompongan Lantai 29 dan 31 (Secondary Link)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Renovasi Relokasi KC Senayan ke Menara BNI Pejompongan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan readymade dan loose furniture pekerjaan renovasi ruang kerja Pengelolaan Produksi & Distribusi Kartu Debit & Prepaid Plaza BNI lantai 13','430000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perpanjangan maintenance perangkat trading communication system DIvisi Tresuri','757000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance dan Lisensi pada Mesin Mainframe',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pengelolaan LED Menara BNI Pejompongan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perabotan/Perlengkapan Tahap 2 Secondary Dealing Room BSD (Peralatan Elektronik)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Relayout Ruang Kerja Divisi DGO Menara BNI lantai 19,20,dan 26','1800000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Sewa Jaringan Komunikasi Internet Work Hub KCP Taman Galaxy Bekasi (Primary Link dan Secondary Link)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Link Dedicated Primary untuk SD-WAN di DC Slipi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Lisensi Berlangganan, Jasa Pemeliharaan dan IT Service Management untuk Perangkat Lunak Platform Container Services BNI Cloud berbasis RedHat',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Jasa Tele Pro Aktivasi Kartu Kredit BNI (01 Sept sd 31 Okt 2022)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan jasa maintenance dan operasional perangkat IP-PBX','1140000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Notebook Office Automation Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Jasa Tele-Usage Loan On Phone Kartu Kredit BNI (Periode 01 Juli sd 30 September 2022)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Tool Push Notification dan Behaviour Analytic',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Migrasi Upgrade Server aplikasi MTeleplus',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultan Struktur Remunerasi & Manajemen Karier dlm rangka Project Organizational Design & Sizing',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Lisensi dan Jasa Implementasi Low Code/No-Code Application Platform (LCAP)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Manajemen Konstruksi Pekerjaan Pembangunan Gudang Arsip KC Dumai',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Lisensi Software Anti Virus',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Sewa Jaringan Internet Menara BNI Pejompongan lantai 29 dan 31 (Primary Link)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pengelolaan LED BNI KC Kramat',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Pemeliharaan CCOS Tahun 2023','557000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Sewa Jasa Content Delivery Network (CDN) dan Fitur Security untuk Akses Aplikasi Ibank, BNIDirect, Web BNI dan Aplikasi BNI Lainnya',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultan Lead Advisor atas Pekerjaan Tambahan Project Srikandi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penambahan Lisensi Software Antivirus Symantec Endpoint Protection',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan TV renovasi ruang kerja Divisi Data Management & Analytics',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Aplikasi Smartdigi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan  Jasa maintenance Sistem Smartbill Kartu Kredit BNI (ERPS dan Virtual EDC)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Tangerang)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pekerjaan IT Quality Assurance Support untuk Testing System Aplikasi TI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Pengawasan Pekerjaan Perbaikan Atap dan Instalasi Listrik Rumah Jabatan Griya Simprug Jakarta Selatan Area A, C, dan E',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Pengelolaan dan Pemeliharaan Gedung BNI Record Centre (BRC) Cikupa',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Outsourcing Pekerjaan Operasi DRC',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Error saat kirim pembukaan penawaran tahap 1',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa IT ( UAT )',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - 6012023 - 2',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Gelap pengadaan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test Workflow Approval Pengadaan Cancel 0 - 100 Jt',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jadwal Pengadaan 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Workflow Approval Gagal  501 jt - infinite',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test re-held 2 sampul',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Kampus Mantap 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Mei 2024',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('konsultan konstruksi 2',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('pengadaan Revisi HPS',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Revisi HPS 2',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan UAT Pelaksana Konstruksi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Lisensi ABBYY FlexiCapture pada Aplikasi Automatic Document Capture','264550000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Renovasi lantai Sentra Kas Divisi Operasional',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Campaign Produk Unggulan BNI melalui platform digital media social',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Pengawasan Pekerjaan Perbaikan Gondola di Plaza BNI BSD','55000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Tools Monitoring Berbasis Event Log','825000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Upgrade Sewa Jaringan Komunikasi Internet Gedung Graha BNI Lantai 25 Primary Link',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Blank Card BNI Mastercard Emerald sebanyak 10.000 pcs Kartu',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Telekomunikasi Kantor Cabang Kudus','133200000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perpanjangan sementara sewa jasa content delivery network (CDN) dan fitur security untuk akses Ibank, BNIDirect dan Web BNI','950160000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 38.471 Unit Sewa EDC Full Managed Service (FMS) PT. Mitra Transaksi Indonesia','73278021960.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan pekerjaan penggantian module hellboard x-ray Smiths Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan workstation dan kursi kerja area Telesales di BNI KCP Matraman dan KCP Mangga Dua Divisi SLN',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Produksi Kalender Dinding BNI Edisi Tahun 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Tangerang dengan PT Swadharma Sarana Informatika (No. PKS awal 11/PKS/PFA/2021 Tanggal 25 Juli 2022)','569624218.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Bekasi dengan PT Sectoor Indonesia (No. PKS awal 08/PKS/PFA/2021 Tanggal 25 Juli 2022)','1027651358.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan workstation dan kursi ruang kerja Divisi Bisnis Korporasi 3 di lantai 3 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat OA PC Desktop Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Pengadaan Konsultan Jasa Executive Search / Head Hunter',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Pemeliharaan Sistem Aplikasi Smart Mobile / MTeleplus',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Pembangunan Digital Center BNI di Gedung Sarinah Lantai 11',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Solusi Cloud Management Platform (CMP)','1900000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Perencanaan Pekerjaan Peningkatan Pengamanan Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Server IBM Power 8 Untuk Sistem Aplikasi SOA','1998000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perpanjangan pengelolaan dan pemeliharaan gedung Wisma Griya BNI Simprug selama 6 (enam) bulan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Link Dedicated Secondary Untuk SD-WAN di DC Slipi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Depok)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Karawang)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 1 Set AC dan instalasi di Ruang Server Dealing Room Plaza BNI BSD',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Roller Blind Ruang Kerja Divisi KPS1, KPS2, KPS3 dan SSK',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Renovasi Aset Permata Hijau Untuk Kebutuhan Ruang Kerja',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perpanjangan Subscription Lisensi Software Tableau Server Core-Based License Model dan Penambahan Fitur Data Management Add On dan Server Management Add On',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pekerjaan Lanjutan Fitting Out Ruang Kerja Sementara Wakil Direktur Utama di Lantai 7 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan HA Database Firewall Security System DC Sudirman',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan loose furniture ruang kerja Syndication & Corporate Solution di lantai 19 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penambahan Lisensi Voice Logger untuk unit verifikasi di SKK dan penagihan di RRW',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Blank Card Kartu Debit BNI Agen46 sebanyak 265.000 pcs kartu',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('PENGADAAN PEKERJAAN WATER LEAK DETECTOR PADA SISTEM BAS (BUILDING AUTOMATION SYSTEM) DI GEDUNG GRHA BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan IT ( Gagal ) UAT',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengadaan Tender Terbatas',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Uji - Pengadaan 28122022 ke 2 - dgm',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UJI - Pengadaan ET  - dgm',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test evaluasi harga friska',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengumuman Tender Terbatas - 10012023 - 02',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan WO Application 2023','300000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Gedung Kampus 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('satu sampul Testing','92000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Monitoring 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Penyesuaian Official Report - PL',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('testing sanggahan 09022023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('TEST APPROVAL',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT Note Teknis',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT UCP Di Bawah  500 Juta 2',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Barang Proses',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test 4 Pengadaan - Konsultan Konstruksi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan UAT Barang Proses',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan ITSM untuk Operasional Harian Exadata dan Exalogic','2650000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat IT Non Otomasi Tahun 2022 - Laptop Divisi KOM 2','399711000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM','235000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultansi Pengawasan Pekerjaan Renovasi Lantai 25 dan Lantai 26 Divisi PDM',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Fitting Out Lantai 4 Wisma 46 untuk Ruang Kerja Sementara Divisi KPS1, KPS2 dan KPS3',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Upgrade Sewa jaringan Komunikasi Internet Gedung Graha BNI Lantai 25 Secondary Link',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan maintenance perangkat Router WAN di Gedung Plaza BNI BSD','287000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultan Pendampingan P3DN Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan PC Spesifikasi Khusus Tahun 2022','2458000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konsultansi Perencanaan Pekerjaan Relayout Ruang Kerja Divisi Pengembangan Digital (DGL)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Maintenance Perangkat Storage IBM DS8886 Core Banking DC-DRC Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Lisensi Virtualisasi Server Development Cardlink','2950000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Genset di Rumah Jabatan BNI Jl. Gandaria III no. 24 Jakarta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pelatihan Mindfulness untuk Program Kepemimpinan BNI','897582500.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan 60.000 Unit Sewa EDC Himbara',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan kursi kerja Divisi Solusi Ritel','96778125.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance dan Support Advanced Anti Malware DC Slipi','1584000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Peremajaan dan Penambahan Server RISC Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Perangkat Security High Availability IPS untuk pengamanan DC Sudirman dan Slipi','3399282033.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perangkat Telekomunikasi IP Phone di Area Ruang Direksi dan SEVP BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan sewa link Metro-E up to 100 Mbps untuk Kebutuhan Aktivitas Split Operation di Gedung Office 88',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Agenda VIP tahun 2023 sebanyak 12.500 buku',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Perjanjian Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/ KCP/KK ke Sentra Kas/ Sub Sentra dan/ atau Sebaliknya Area Jakarta Barat dengan PT Swadharma Sarana Informatika (No. PKS awal 13/PKS/PFA/2021 Tanggal 25 Juli 2022)','417263853.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Manage Service dan Maintenance Platform FSCM',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Pengelolaan/Maintenance Security System BNI periode  2023-2024',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES (NULL,'General Manager',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan penyedia layanan tools dan operator live streaming/tapping dan hybrid suplemen pengetahuan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pekerjaan Penanggulangan Banjir Gedung Menara BNI','1830000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('PERPANJANGAN MAINTENANCE APLIKASI  ENTERPRISE RECONSILIATION SYSTEM CITYNET',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pekerjaan Jasa Konstruksi Renovasi Rumah Pompa Pemadam Kebakaran dan Modifikasi Cadangan GWT Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Maintenance Aspect Predictive Dialer System (PDS) Versi 7 di 4 Kota dan Bisnis Banking',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Maintenance dan Blanket Mandays Aplikasi BARS',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Lisensi Microfocus Visual Cobol Dalam Negeri',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan loose furniture ruang kerja Divisi Bisnis Korporasi 1 di lantai 16 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Hardscape dan Landscape Aset Permata Hijau',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Local Support Aplikasi LIAPP-RASP',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan loose furniture ruang kerja Corporate Banking 2 di lantai 11 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan jasa pelaksana perbaikan interior area Telesales KCP Matraman dan KCP Mangga Dua',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Instalasi UTP LAN di Lantai 28 - 31 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Sewa EDC Full Managed Service 15.000 Unit',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Server Aplikasi BNI Direct Mobile di DC Slipi Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa SLM ATM PT Jalin Pembayaran Nusantara',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Pembuatan Shelter Ojek Online dan Tempat Parkir Sepeda Motor Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Upgrade Sewa Jaringan Komunikasi Internet DC Slipi (Primary Link) 500 Mbps',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Security Data Center WAN Block',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pemeliharaan (Kontrak Servis) HVAC Gedung Grha Sudirman',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Aplikasi ( Ulang )',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengadaan Pengumuman - dgm',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Uji - Pengadaan Pengumuman Tender Terbatas - 10012023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('TESTING',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Iseng Beli Laptop',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Workflow Approval pengadaan Cancel 0 - 100 jt',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Coba testing',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT 22052023  (Perpanjangan Pengumuman )',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('testing1',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('pengadaan percetakan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Test 5 Pengadaan - Barang Proses',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaaan Maintenance Server DPLK dan Remittance Tahun 2022','1850000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Enterprise Event Bus',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Office Automation PC High End Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Renovasi Rumah Dinas Slipi Blok L1',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan All in One PC Aplikasi DigiCS Lite',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Operasional Harian untuk Mendukung Layanan BNI e-Payment','955000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Lisensi Berlangganan dan Jasa Pemeliharaan Perangkat Lunak Platform Container Service BNI Cloud','2053951770.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Upgrade Sewa Jaringan Komunikasi Internet Menara BNI Pejompongan (Primary dan Secondary Link)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Pengelolaan dan Pemeliharaan Gedung BNI Record Center (BRC) Cikupa selama 6 (Enam) Bulan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan peralatan digital communication studio, peralatan live streaming, broadcasting dan podcast BNI Corporate University','2050000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Software IBM SOA',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Maintenance Perangkat Backup Virtual Tape Library (VTL) BNI','2200020000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan workstation dan kursi ruang kerja Divisi Bisnis Korporasi 1 di lantai 16 Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan karpet lantai site BNI KCP Matraman dan KCP Mangga Dua Divisi SLN',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan maintenance Hardware Kondor+ dan KTP Tahun 2022','950000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Pemeliharaan New Website BNI','288000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Perangkat Office Automation Printer Passbook Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Hardware Mesin Mainframe IBM zSeries Z12 DRC Jatiluhur',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Taktikal Penambahan Jasa Tele-Usage Loan On Phone (LOP) Kartu Kredit BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Buku Tabungan BNI Taplus Tahun 2022','1792500000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pekerjaan Water Leak Detector Pada Sistem BAS (Building Automation System) di Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Perangkat Security IPS DC Slipi Area DMZ',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan EDC Android Middleware Platform',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Renovasi Ruang Kerja Unit Collection di Gedoeng BNI Lantai 3',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Lisensi Microfocus Cobol untuk Core Banking System KCLN Tokyo, London, New York dan Seoul',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konstruksi Pekerjaan Pembangunan Outlet Emerald High End Melawai',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Jasa Pemeliharaan Velis Token Aunthentication System',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Perangkat Storage Surrounding dan Email BNI Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Endpoint Detection & Response',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Blank Card Kartu Debit Chip Mastercard sebanyak 100.000 pcs kartu',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Perencanaan Pekerjaan Relayout Outlet Emerald Central Park',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan perangkat office automation Router tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Pengangkutan Uang Tunai (Pick Up Service) dari KCU/KCP/KK ke Sentra Kas/ Sub Sentra dan/atau Sebaliknya (Area Bekasi)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Roller Blind Ruang Kerja Direksi dan Komisaris Lantai 28 s/d 31 Gedung Grha BNI',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Jasa Konsultansi Manajemen Konstruksi Renovasi KCP Merdeka Selatan',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Solusi Self Services Management Akun Active Directory',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Perpanjangan Maintenance Konsolidasi Server SPARC T7 DC Slipi Tahun 2022',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Pengelolaan & Pemeliharaan Bangunan BNI di Jalan Sultan Hasanudin No.3-4 Jakarta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Jasa Konstruksi Pekerjaan Renovasi Toilet, Pantry dan Gudang Lantai 10 Grha BNI Divisi Compliance',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan TENDER untuk Maintennance Applikasi',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan TENDER TERBATAS jasa Maintenance','450000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengadaan Jasa',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT Pengadaan ET - pimkel',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan friska',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan pembelian laptop ngabisin anggaran',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - 05012023 - 01',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('UAT - Pengumuman Tender - 10012023 - 02',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Gedung XYZ',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Membuat Pengadaan TESTING',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Cloud Server 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan Test Workflow Approval Cancel 501 jt - infinite',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan dibawah 500juta - Jan 2023',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Inisiasi Pengadaan testing',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test re-held 2 tahap','440000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Pengadaan test re-held 2 sampul','1270000000.00',NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Data UAT 22052023  (MultiWinner UCP)',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('testing inisiasi dibawah 500 juta',NULL,NULL,NULL);
INSERT INTO monitoring_pembayaran_rutin(NAMA,NILAI_PENGADAAN_HASIL,Pembayaran_Terakhir,Status_Jatuh_Tempo) VALUES ('Tes 2 Pengadaan (Barang Jadi  Distributor)',NULL,NULL,NULL);
